[pytest]
DJANGO_SETTINGS_MODULE = charmaway.settings
python_files = tests.py

filterwarnings =
    ignore::DeprecationWarning:requests.auth
    ignore::django.utils.deprecation.RemovedInDjango60Warning