# Generated by Django 5.2.8 on 2025-11-23 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_customer_is_active_customer_is_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='prefered_payment_method',
            field=models.CharField(default='Tarjeta de crédito', max_length=50),
        ),
    ]
