# Generated by Django 5.2.8 on 2025-11-20 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_order_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='uuid',
        ),
        migrations.AddField(
            model_name='order',
            name='public_id',
            field=models.CharField(default='GvRfrbCmUraE', editable=False, max_length=12, unique=True),
        ),
    ]
