# Generated by Django 5.2.8 on 2025-11-21 20:43

import order.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_remove_order_uuid_order_public_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='public_id',
            field=models.CharField(default=order.models.generate_unique_public_id, editable=False, max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PROCESSING', 'Processing'), ('SHIPPED', 'Shipped'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], default='PROCESSING', max_length=20),
        ),
    ]
