# Generated by Django 5.2.8 on 2025-11-25 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_order_delivery_option_alter_order_status'),
        ('services', '0003_alter_service_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='services.service'),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='services.service'),
        ),
    ]
