# Generated by Django 5.2.8 on 2025-11-13 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_catalog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='productsize',
            options={'ordering': ['size']},
        ),
    ]
