# Generated by Django 5.2.8 on 2025-11-25 02:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_department_category_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories', to='catalog.department'),
        ),
    ]
